import { useEffect, useState } from 'react';
import { nativePhone } from './app-ui';
type Device={id:string;name:string;created:number;expires:number};
async function pairing(route:string,body?:unknown){const r=await fetch('/api/pairing'+route,{method:body?'POST':'GET',headers:{'X-Hermes-Mobile':'1',...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});const v=await r.json();if(!r.ok)throw Error(v.error);return v;}
export default function Pairing(){const [devices,setDevices]=useState<Device[]>([]),[origin,setOrigin]=useState(''),[code,setCode]=useState(''),[expires,setExpires]=useState(0),[error,setError]=useState(''),[busy,setBusy]=useState(false),[remaining,setRemaining]=useState(0);
  async function refresh(){try{const v=await pairing('/');setDevices(v.devices);setOrigin(v.origin||'');}catch(e){setError((e as Error).message);}}
  useEffect(()=>{if(!nativePhone)void refresh();},[]);
  useEffect(()=>{const update=()=>setRemaining(Math.max(0,Math.ceil((expires-Date.now())/1000)));update();const id=setInterval(update,1000);return()=>clearInterval(id);},[expires]);
  async function mint(){setBusy(true);setError('');try{const v=await pairing('/code',{});setCode(v.code);setExpires(v.expires);await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function revoke(id:string){setBusy(true);try{await pairing('/revoke',{id});await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function logout(){setBusy(true);try{const r=await fetch('/api/device/logout',{method:'POST',headers:{'X-Hermes-Mobile':'1','Content-Type':'application/json'},body:'{}'});if(!r.ok)throw Error('Could not disconnect. Try again.');Object.keys(sessionStorage).filter(k=>k.startsWith('hermes.')).forEach(k=>sessionStorage.removeItem(k));location.reload();}catch(e){setError((e as Error).message);setBusy(false);}}
  return <div className="settings-row"><strong>{nativePhone?'Paired with Omarchy':'Connect your phone'}</strong>{nativePhone?<><p>This device can access your Hermes profiles and conversations. Manage paired devices from this computer.</p><button className="wide-button secondary" disabled={busy} onClick={()=>void logout()}>Disconnect this device</button></>:<><p>Connect your phone to the same Tailscale network, open the private address, then enter a code from this computer.</p>{origin?<a className="phone-address" href={origin} target="_blank" rel="noreferrer">{origin}</a>:<p>Private phone access has not been configured.</p>}<button className="wide-button" disabled={busy||!origin} onClick={()=>void mint()}>Generate pairing code</button>{code&&<div className="pair-code" aria-live="polite"><strong>{remaining?code:'Expired'}</strong><p>{remaining?`Single use · ${Math.floor(remaining/60)}:${String(remaining%60).padStart(2,'0')} remaining`:'Generate a new code to connect.'}</p></div>}<div className="paired-devices"><strong>Paired devices</strong><button className="wide-button secondary" disabled={busy} onClick={()=>void refresh()}>Refresh device list</button>{devices.map(d=><div className="paired-device" key={d.id}><span>{d.name}<small>Expires {new Date(d.expires).toLocaleDateString()}</small></span><button disabled={busy} onClick={()=>void revoke(d.id)}>Revoke</button></div>)}{!devices.length&&<p>No devices paired yet.</p>}</div></>}{error&&<p role="alert">{error}</p>}</div>;
}
