import { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import Prototype from './Prototype';
import './prototype.css';
import './phone.css';
function Phone(){const [paired,setPaired]=useState(false),[loading,setLoading]=useState(true),[code,setCode]=useState(''),[name,setName]=useState('My phone'),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  useEffect(()=>{const expire=()=>{setPaired(false);setError('Your connection has expired or was revoked. Pair again to continue.');};window.addEventListener('hermes-auth-expired',expire);fetch('/api/device/session',{headers:{'X-Hermes-Mobile':'1'}}).then(r=>{if(r.ok)setPaired(true);else if(r.status!==401)setError('The host is unavailable. Reload to retry.');}).catch(()=>setError('Cannot reach Omarchy. Check Tailscale, then reload.')).finally(()=>setLoading(false));
    const view=()=>{const v=window.visualViewport;document.documentElement.style.setProperty('--phone-height',`${v?.height||innerHeight}px`);document.documentElement.style.setProperty('--phone-top',`${v?.offsetTop||0}px`);};view();window.visualViewport?.addEventListener('resize',view);window.visualViewport?.addEventListener('scroll',view);return()=>{window.removeEventListener('hermes-auth-expired',expire);window.visualViewport?.removeEventListener('resize',view);window.visualViewport?.removeEventListener('scroll',view);};},[]);
  async function pair(){setBusy(true);setError('');try{const r=await fetch('/api/device/pair',{method:'POST',headers:{'X-Hermes-Mobile':'1','Content-Type':'application/json'},body:JSON.stringify({code,name})});const v=await r.json();if(!r.ok)throw Error(v.error);setCode('');setPaired(true);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  if(paired)return <Prototype/>;return <div className="pair-page"><img src="/hermes-emblem.png" alt=""/><p className="eyebrow">HERMES RELAY</p><h1>Your agents.<br/>Wherever you are.</h1><p>Connect securely to your Omarchy machine.</p>{loading?<p role="status">Checking your connection…</p>:<form onSubmit={e=>{e.preventDefault();void pair();}}><label>Device name<input value={name} maxLength={60} onChange={e=>setName(e.target.value)} autoComplete="off"/></label><label>Pairing code<input value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,'').slice(0,6))} inputMode="numeric" pattern="[0-9]{6}" autoComplete="one-time-code" placeholder="000000" required/></label><p>On your computer, open Settings → Generate pairing code.</p><button disabled={busy||code.length!==6}>{busy?'Connecting…':'Connect to Omarchy'}</button></form>}{error&&<p role="alert">{error}</p>}<p className="pair-footnote">Private connection · Your API keys stay on the host</p></div>;
}
createRoot(document.getElementById('root')!).render(<Phone/>);
