import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import http from 'node:http';import {once} from 'node:events';
import {createDevices} from '../server/devices.mjs';
import {phoneHandler,localPairingHandler,cookieName} from '../server/phone-server.mjs';
function fixture(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'hermes-pair-test-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));let now=100000;const devices=createDevices(dir,()=>now);return {dir,devices,advance:n=>now+=n};}
test('codes are single use, expire, burn after eight wrong attempts, and persist only hashes',t=>{const f=fixture(t);const {code}=f.devices.mint();const {token,device}=f.devices.pair(code,'Test phone');const disk=fs.readFileSync(path.join(f.dir,'devices.json'),'utf8');assert.ok(!disk.includes(token));assert.ok(!disk.includes(code));assert.equal(f.devices.authenticate(token).id,device.id);assert.throws(()=>f.devices.pair(code,'again'));f.devices.revoke(device.id);assert.equal(f.devices.authenticate(token),null);
 const second=f.devices.mint();for(let i=0;i<8;i++)assert.throws(()=>f.devices.pair('bad','no'));assert.throws(()=>f.devices.pair(second.code,'late'));const third=f.devices.mint();f.advance(600001);assert.throws(()=>f.devices.pair(third.code,'late'));
 const fourth=f.devices.mint();const d=f.devices.pair(fourth.code,'valid');f.advance(30*86400000);assert.equal(f.devices.authenticate(d.token),null);assert.deepEqual(f.devices.list(),[]);});
async function start(t,handler){const s=http.createServer(handler);s.listen(0,'127.0.0.1');await once(s,'listening');t.after(()=>s.close());return 'http://127.0.0.1:'+s.address().port;}
function request(url,options={}){return new Promise((resolve,reject)=>{const req=http.request(url,{method:options.method||'GET',headers:options.headers},res=>{const chunks=[];res.on('data',c=>chunks.push(c));res.on('end',()=>resolve(new Response(Buffer.concat(chunks),{status:res.statusCode,headers:res.headers})));});req.on('error',reject);req.end(options.body);});}
const origin='https://fixture.tail123.ts.net:8443';
const headers={host:new URL(origin).host,origin,'x-hermes-mobile':'1','content-type':'application/json','sec-fetch-site':'same-origin'};
test('remote API requires pairing, exact origin, secure cookie and fresh revocation checks',async t=>{const f=fixture(t);let calls=0;const url=await start(t,phoneHandler({devices:f.devices,origin,staticDir:f.dir,dispatch:async()=>{calls++;return {ok:true};}}));
 assert.equal((await request(url+'/api/mobile/profiles',{headers})).status,401);assert.equal(calls,0);
 const {code}=f.devices.mint();const r=await request(url+'/api/device/pair',{method:'POST',headers,body:JSON.stringify({code,name:'fixture'})});assert.equal(r.status,200);const cookie=r.headers.get('set-cookie');assert.match(cookie,/HttpOnly; Secure; SameSite=Strict/);assert.ok(cookie.startsWith(cookieName+'='));const body=await r.json();assert.equal(body.token,undefined);const auth={...headers,cookie:cookie.split(';')[0]};
 assert.equal((await request(url+'/api/mobile/profiles',{headers:auth})).status,200);assert.equal(calls,1);
 for(const extra of [{host:'evil.test'},{origin:'https://evil.test'},{'sec-fetch-site':'cross-site'},{'x-hermes-mobile':''}])assert.equal((await request(url+'/api/mobile/profiles',{headers:{...auth,...extra}})).status,403);
 assert.equal((await request(url+'/api/pairing/code',{method:'POST',headers:auth,body:'{}'})).status,404);
 f.devices.revoke(body.device.id);assert.equal((await request(url+'/api/mobile/profiles',{headers:auth})).status,401);assert.equal(calls,1);
});
test('private server serves only build assets and bounds request bodies',async t=>{const f=fixture(t);fs.writeFileSync(path.join(f.dir,'phone.html'),'<html>Phone</html>');fs.writeFileSync(path.join(f.dir,'.env'),'secret');const url=await start(t,phoneHandler({devices:f.devices,origin,staticDir:f.dir,dispatch:()=>assert.fail()}));assert.equal((await request(url+'/',{headers:{host:headers.host}})).status,200);assert.equal((await request(url+'/.env',{headers:{host:headers.host}})).status,404);assert.equal((await request(url+'/src/Phone.tsx',{headers:{host:headers.host}})).status,404);assert.equal((await request(url+'/api/device/pair',{headers,method:'POST',body:JSON.stringify({code:'1'.repeat(25000)})})).status,413);});
test('only the local preview can create codes and revoke devices',async t=>{const f=fixture(t);const url=await start(t,localPairingHandler({devices:f.devices,origin}));assert.equal((await request(url+'/code',{method:'POST',headers,body:'{}'})).status,403);const local={...headers,host:'127.0.0.1:4186',origin:'http://127.0.0.1:4186'};const r=await request(url+'/code',{method:'POST',headers:local,body:'{}'});assert.equal(r.status,200);assert.match((await r.json()).code,/^\d{6}$/);});
